# Build options
url: https://matthewlincoln.net
timezone: America/Los_Angeles
permalink: /:year/:month/:day/:title.html
markdown: kramdown
future: false
enable_analytics: true
gems:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
