# Build options
url: http://matthewlincoln.net
timezone: America/New_York
pygments: true
permalink: /:year/:month/:day/:title.html
markdown: kramdown
future: false
enable_analytics: true
enable_disqus: true
