# Build options
url: https://matthewlincoln.net
timezone: America/Los_Angeles
permalink: /:year/:month/:day/:title.html
markdown: kramdown
future: false
enable_analytics: true
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - _local_config.yml
  - node_modules
  - package-lock.json
  - package.json
  - assets/js/main.js
  - assets/js/bundle.js.tmp*
