title: Matthew Lincoln
subtitle: Art History Ph.D student, University of Maryland
pygments: true
permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown
url: http://matthewlincoln.net
future: false
timezone: America/New_York
