title: Matthew Lincoln
name_first: Matthew D.
name_last: Lincoln
position: PhD Candidate
tagline: "Art History and Digital Research"
description: "The personal blog of Matthew D. Lincoln, PhD candidate in the Department of Art History and Archaeology, University of Maryland, College Park."
