title: Matthew Lincoln, PhD
name_first: Matthew D.
name_last: Lincoln
position: PhD
tagline: "Art History and Digital Research"
description: "The personal blog of Matthew D. Lincoln, PhD, data research specialist at the Getty Research Institute."
