title: Matthew Lincoln, PhD
name_first: Matthew D.
name_last: Lincoln
position: PhD
tagline: "Art History and Digital Research"
description: "The personal blog of Matthew D. Lincoln, PhD in the Department of Art History and Archaeology, University of Maryland, College Park."
