title: Matthew Lincoln, PhD
name_first: Matthew D.
name_last: Lincoln
position: PhD
tagline: Cultural Heritage Data & Info Architecture
description: |
  The personal blog of Matthew D. Lincoln, PhD, Collections Information Architect at Carnegie Mellon University.
