# Site information
title: Matthew Lincoln
description: "The personal blog of Matthew D. Lincoln, Ph. D student in the Department of Art History and Archaeology, University of Maryland, College Park."
banner:
    name: 'Hendrick Goltzius, detail of "Portrait of Philip Galle", 1582, engraving, Rijksmuseum'
    source: https://www.rijksmuseum.nl/en/collection/RP-P-OB-10.148
    img: /assets/images-display/header.png
