# Site information
title: Matthew Lincoln
banner:
    name: 'Hendrick Goltzius, detail of "Portrait of Philip Galle", 1582, engraving, Rijksmuseum'
    source: https://www.rijksmuseum.nl/en/collection/RP-P-OB-10.148
    img: /assets/images-display/header.png
