backend:
  name: github
  repo: mdlincoln/mdlincoln.github.io
publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "assets/images"
site_url: https://matthewlincoln.net
display_url: https://matthewlincoln.net
collections:
  - name: post
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    label: "Post"
    description: "Add, delete, and edit pages on the site."
    folder: "_posts"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: datetime
      - name: body
        label: Content
        widget: markdown
      - name: "tags"
        label: "Tags"
        widget: "select"
        options: ["academia", "art_history", "articles", "books", "code", "computer_vision", "conferences", "data", "digital_humanities", "gis", "humanities", "lam", "network_analysis", "publishing", "r", "teaching", "thatcamp", "us-rse", "visualization"]
        multiple: true
      - name: "aside"
        label: "Aside"
        widget: markdown
        required: false
      - name: layout
        label: Layout
        widget: hidden
        default: post
