backend:
  name: github
  repo: mdlincoln/mdlincoln.github.io
publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "assets/images"
site_url: https://matthewlincoln.net
display_url: https://matthewlincoln.net
collections:
  - name: post
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    label: "Post"
    description: "Add, delete, and edit pages on the site."
    folder: "_posts"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: datetime
      - name: "tags"
        label: "Tags"
        widget: "select"
        options: ["Academia", "Art History", "Articles", "Books", "Code", "Computer Vision", "Conferences", "Data", "Digital Humanities", "GIS", "Humanities", "LAM", "Network Analysis", "Publishing", "R", "Teaching", "THATCamp", "US-RSE", "Visualization"]
        multiple: true
      - name: layout
        label: Layout
        widget: hidden
        default: post
      - name: body
        label: Content
        widget: markdown
      - name: "aside"
        label: "Aside"
        widget: markdown
        required: false
  - name: settings
    label: Settings
    description: Site settings
    files:
      - label: Travel
        name: travel
        file: "_data/travel.yaml"
        fields:
          - label: entries
            name: entries
            widget: list
            fields:
              - {name: venue, label: venue, widget: string}
              - {name: location, label: location, widget: string}
              - {name: url, label: url, widget: string}
              - {name: Start date, label: datestart, widget: datetime, format: YYYY-MM-DD HH:MM:SS Z}
              - {name: End date, label: dateend, widget: datetime, default: "", format: YYYY-MM-DD HH:MM:SS Z}

